spring.datasource:
  #url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://mysql:3306/globalinsurancedb?useSSL=true&nullCatalogMeansCurrent=true 
  username: root
  password: password
#spring.h2.console.enabled: true
spring.jpa.hibernate.ddl-auto: update
 
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
#  default-serialization-format: application/json
server.port: 7080
