version: '3.9'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=policydb
    volumes:
      - /data/mysql
    healthcheck:        
        interval: 30s
        timeout: 10s
        retries: 5
  
  policy-app:
    image: policyapp
    build:
      context: ./
      dockerfile: dockerfile
    depends_on:
      - mysql
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 15
        window: 50s
    ports:
       #- 8060-8070:7070
        - 7074:7070
    volumes:
      - /data/compose-app

  